### ISSUE TITLE
Browser action doesn't work with linked images

### ISSUE THREAD

**Issue by seth10** [sethten/pinterest-permissions#1]
If an image has some event attached to it, that is taking precedence. After testing with a simple alert call in [background.js](/sethten/pinterest-permissions/blob/browser-action-usability/background.js/#L29), I can confirm the message is getting passed, but the notification is not being created.
### Relevant:
- [`event.preventDefault();`](/sethten/pinterest-permissions/blob/67d19c8a497fb7a5cf6c3a1833ab2f668fb650f3/ClickGetImg.js#L21)
- [`document.addEventListener(`...`false);`](/sethten/pinterest-permissions/blob/67d19c8a497fb7a5cf6c3a1833ab2f668fb650f3/ClickGetImg.js#L25)
- [`spotlightStyle.innerHTML = '`...`pointer-events: none;`](/sethten/pinterest-permissions/blob/67d19c8a497fb7a5cf6c3a1833ab2f668fb650f3/ClickGetImg.js#L37)

**Comment by seth10** [comment]
Turns out this is because of [Chrome's Content Security Policy](https://developer.chrome.com/extensions/contentSecurityPolicy). The [imageUrl](https://developer.chrome.com/extensions/notifications#property-NotificationOptions-iconUrl) for a notification "can be a data URL, a blob URL, or a URL relative to a resource within this extension's .crx file." I tried [using a canvas element](https://davidwalsh.name/convert-image-data-uri-javascript) to create a data URL, but I get the following error:

```
Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```

When targeting images on dedicated pages (such as `http://img05.imageHosting.net/path/1234.png`), however, this did work. There was also no problem using the images from the [Chrome debugging tutorial page](https://developer.chrome.com/extensions/tut_debugging). As these are the images I used for most of my testing, everything appeared to be working except for in special cases. On most images the following error is produced:

```
Unchecked runtime.lastError while running notifications.create: Unable to download all specified images.
at snip (chrome-extension://aolmflleialcdjpmjhmimmkedokdlnfi/background.js:35:24)
at chrome-extension://aolmflleialcdjpmjhmimmkedokdlnfi/background.js:31:5
```

This seems pretty final for this issue, so it is being closed without resolution. Another method for showing users the image might be applied, perhaps the CSP will allow it in popup.html or a new tab.

**Comment by seth10** [comment]
I have one other observation that may be worth preserving. I attempted to use the browser action to snip an image on DeviantArt. Nothing happened, now I know that if I had opened the extension's background page I would have seen `Unable to download all specified images`. I opened the context menu for the image and selected `Open Image in New Tab`. Now on a tab of just the image, I once again attempted to invoke the browser action, and this time the notification did open with the image. I went back to the original DeviantArt page and now it worked here too.

**Comment by seth10** [comment]
Taking a cursory attempt at using the same method I [used in FicBot](/sethten/ficbot/blob/master/getChapter.js) yielded

```
_generated_background_page.html:1 XMLHttpRequest cannot load http://img05.deviantart.net/___.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://aolmflleialcdjpmjhmimmkedokdlnfi' is therefore not allowed access.
```

Code added in [background.js](/sethten/pinterest-permissions/blob/67d19c8a497fb7a5cf6c3a1833ab2f668fb650f3/background.js#L23):

```
chrome.runtime.onMessage.addListener( function(request, sender, sendResponse) {
  var get_req = new XMLHttpRequest();
  get_req.open('GET', request.image, true);
  get_req.responseType = 'blob';
  get_req.send();

  get_req.onload = function() {
    snip(URL.createObjectURL(get_req.response));
  };
});
```
